/* AUTO-GENERATED by RatEngineGUI - do not edit manually */
#include "sprite_ids.h"

const char* SPRITE_NAMES[SPRITE_COUNT] = {
    [SPRITE_NONE] = "none",
    [SPRITE_YELLOW] = "yellow",
    [SPRITE_RED] = "red",
};

const SpriteAtlasEntry SPRITE_ATLAS_DATA[SPRITE_COUNT] = {
    [SPRITE_NONE] = { .total_frames = 0 },
    [SPRITE_YELLOW] = { .frames = {{0.0f,0.0f,8.0f,8.0f},{8.0f,0.0f,8.0f,8.0f}}, .total_frames = 2 },
    [SPRITE_RED] = { .frames = {{16.0f,0.0f,8.0f,8.0f},{24.0f,0.0f,8.0f,8.0f}}, .total_frames = 2 },
};
