/* AUTO-GENERATED by RatEngineGUI - do not edit manually */
#ifndef SPRITE_IDS_H
#define SPRITE_IDS_H

#include <raylib.h>

#define MAX_SPRITE_FRAMES 16

typedef enum SpriteID {
    SPRITE_NONE = 0,
    SPRITE_YELLOW,
    SPRITE_RED,
    SPRITE_COUNT
} SpriteID;

extern const char* SPRITE_NAMES[SPRITE_COUNT];

typedef struct SpriteAtlasEntry {
    Rectangle frames[MAX_SPRITE_FRAMES];
    int total_frames;
} SpriteAtlasEntry;

extern const SpriteAtlasEntry SPRITE_ATLAS_DATA[SPRITE_COUNT];

#endif /* SPRITE_IDS_H */
